Fastqfilterer replace sickle
EdinburghGenomics/Analysis-Driver pull request #189
Opened 2016-10-13 14:37 UTC by tcezard

2016-10-13 15:33 UTC, katieemelianova commented
Looks good!

2016-10-14 11:28 UTC, mwhamgenomics requested changes

2016-10-14 11:28 UTC, mwhamgenomics commented on analysis_driver/util/bash_commands.py
> +    cmd = "set -o pipefail; %s --i1 %s --i2 %s --o1 >($pigz -p %s > %s) --o2 >($pigz -p %s > %s) --threshold 36"
`$pigz` must be from an example Bash script! This should be `pigz -c`. Would also be good to make this (and the threshold) configurable.

2016-10-18 10:21 UTC, mwhamgenomics approved these changes

2016-10-18 10:38 UTC, merged