early contamination check
EdinburghGenomics/Analysis-Driver pull request #190
Opened 2016-10-19 12:38 UTC by katieemelianova

2016-10-19 13:28 UTC, tcezard requested changes

2016-10-19 13:28 UTC, tcezard commented on analysis_driver/quality_control/contamination_blast.py
> +        seqtk_sample_cmd = '%s sample %s 3000 | seqtk seq -a > %s' % (seqtk_bin, fastq_file, fasta_outfile)
You should use seqtk bin in both instances and also set ```pipefail -o ``` like so
```python
'set pipefail -o; {seqtk} sample {fastq} 3000 | {seqtk} seq -a > {fasta}'.format(seqtk=seqtk_bin, fastq=fastq_file, fasta= fasta_outfile)
```

2016-10-19 13:28 UTC, tcezard commented on analysis_driver/quality_control/contamination_blast.py
> +        ncbi = NCBITaxa()
Need to specify the location of the database with 
```python
ncbi = NCBITaxa(db_file=cfg['contamination-check']['taxa_db'])
```

2016-10-19 13:28 UTC, tcezard commented on analysis_driver/quality_control/contamination_blast.py
> +        blast_cmd = "%s -query %s -db %s -out %s -outfmt '6 qseqid sseqid length pident evalue sgi sacc staxids sscinames scomnames stitle'" % (blastn_bin, fasta_file, nt_db, blast_outfile)
Is the blast command meant to be multithreaded?
The process has been given 2 CPU but could probably be given more.

2016-10-19 13:28 UTC, tcezard commented on analysis_driver/quality_control/contamination_blast.py
> +        return taxa_identified
I think those taxa identified ought to be written to file. maybe in some kind of json format.

2016-10-24 14:00 UTC, katieemelianova commented on analysis_driver/quality_control/contamination_blast.py
> +        taxa_identified = {}
Use Counter here and in other examples of this

2016-10-28 12:56 UTC, mwhamgenomics submitted a review, later dismissed

2016-10-28 12:56 UTC, mwhamgenomics commented on analysis_driver/quality_control/contamination_blast.py
> +        if self.check_db_exists(db_path):
Surely it would be simpler just to do something like:

``` python
def taxon_info(self, taxon, db_path):
    if not os.path.exists(db_path):
        raise AnalysisDriverError('Cannot locate the ETE taxon database')
    # rest of the method...
```

This way we wouldn't need `check_db_exists` above, which doesn't really do much in itself.

2016-10-28 16:04 UTC, mwhamgenomics commented on requirements.txt
>  git+https://github.com/EdinburghGenomics/EGCG-Core.git@v0.4.2
This should be EGCG-Core 0.5

2016-10-28 20:03 UTC, tcezard approved these changes

2016-11-14 15:10 UTC, mwhamgenomics requested changes

2016-11-14 15:10 UTC, mwhamgenomics commented on tests/assets/blast_outfile
> +E00306:25:HCHK3CCXX:1:1101:22404:71524	gi|7768696|dbj|AP001683.1|	130	80.000	8.48e-17	7768696	AP001683	9606	Homo sapiens	human	Homo sapiens genomic DNA, chromosome 21q, section 27/105
The untrimmed test data is still here.

2016-11-24 12:10 UTC, mwhamgenomics approved these changes

2016-11-28 11:50 UTC, merged