Pipeline stopping
EdinburghGenomics/Analysis-Driver pull request #204
Opened 2016-11-08 16:33 UTC by mwhamgenomics

The pipeline now reacts to `15` termination signals, and cleanly sends notifications and stops any running cluster jobs. Note that other signals are not caught.

A running pipeline can be sent a sigterm either by pid via `kill -15`, or by dataset name via `edingen_analysis_driver.py --stop <dataset_names>`.

2016-11-08 17:54 UTC, mwhamgenomics commented
The pid comes from the reporting app and is not removed in the event of an uncaught exception, so could be left out of date. At the moment in `analysis_driver --stop`, there's no checking of the pid to make sure it's a valid pipeline process. Could it be possible that we end up stopping a different pid from what we intended (pipelines, other processes, etc)?

2016-11-09 09:41 UTC, tcezard requested changes

2016-11-09 09:41 UTC, tcezard commented on analysis_driver/client.py
> +                os.kill(pid, 15)
Can we change the signal to 10 (USR1) to have something specific to analysis driver so we can distinguish between process killed by analysis driver or by something else

2016-11-09 09:41 UTC, tcezard commented on analysis_driver/client.py
> +    signal.signal(15, _sigterm_handler)
Can you also trap signal 10 with the same handler?

2016-11-09 09:41 UTC, tcezard commented on analysis_driver/client.py
> +        ntf.crash_report(stacktrace)
This line will never be reached as _handle_termination() call sys.exit().

2016-11-09 09:41 UTC, tcezard commented on analysis_driver/client.py
> +        ntf.crash_report(stacktrace)
We should call crash_report in _handle_termination.
We need the the notification to be triggered (Asana or email) and the stacktrace will be useful to know when/where the process was stopped.

2016-11-09 11:21 UTC, mwhamgenomics commented on analysis_driver/client.py
> +        ntf.crash_report(stacktrace)
It looks like there's only a stacktrace to log if there's a `KeyboardInterrupt` (signal 2).

`_handle_termination` will call notifications via `dataset.fail` with the signal number as the exit status. Is this enough information, or would we like an explicit `dataset.sigterm` (or whatever)?

2016-11-10 10:35 UTC, tcezard approved these changes

2016-11-16 17:10 UTC, merged