Multiple genomes per species
EdinburghGenomics/Analysis-Driver pull request #221
Opened 2017-02-17 14:57 UTC by katieemelianova

Support multiple genomes, using the 'Genome Version' udf from the Lims.
Due to this udf being used before to check for BCBIO genome version, the BCBIO genome version now automatically defaults to the genome set in the config.

2017-02-20 12:44 UTC, tcezard requested changes
`pipeline` should be cleanned a bit to only be resonsible for launching the expected pipeline.
It would be cleaner to have the genome_version selection as a function in common (including raising  exceptions) and call it in the specific pipeline when needed.

2017-02-20 12:44 UTC, tcezard commented on analysis_driver/pipelines/__init__.py
> +            reference = cfg.query('genomes', genome_version, 'fasta')
This should be:
```python
if genome_version is None:
    genome_version = cfg.query('species', species, 'default')
reference = cfg.query('genomes', genome_version, 'fasta')
```
since there isn't any `default` in `genome_version` anymore

2017-02-20 12:44 UTC, tcezard commented on analysis_driver/pipelines/__init__.py
> +            return bcbio_var_calling_pipeline(dataset, bcbio_genome, analysis_type)
bcbio's `genome_version` won't be working anymore as it will force to use `bcbio_genome`

2017-02-20 12:44 UTC, tcezard commented on analysis_driver/pipelines/qc_pipelines.py
>          raise PipelineError('Could not find reference for species %s in sample %s ' % (species, sample_id))
We should move this exception to when we look for the version

2017-02-21 15:32 UTC, tcezard approved these changes

2017-02-28 12:55 UTC, mwhamgenomics commented on analysis_driver/pipelines/common.py
> +    return cfg.query('genomes', genome_version, 'known_indels')
Do we really need these functions? They don't really do much themselves and are only called once each in variant_calling

2017-03-02 14:24 UTC, tcezard commented on analysis_driver/pipelines/common.py
> +    return cfg.query('genomes', genome_version, 'known_indels')
I think that's fine.
They might be used more once we start the segmentation

2017-03-02 14:33 UTC, merged