Early samplesheet loading
EdinburghGenomics/Analysis-Driver pull request #230
Opened 2017-03-03 13:44 UTC by katieemelianova

Starts the run process as soon as the run is available/has started sequencing
Needs to still be merged later with Murray's bcl validation function

2017-03-03 14:01 UTC, tcezard requested changes

2017-03-03 14:01 UTC, tcezard commented on analysis_driver/pipelines/demultiplexing.py
> +    while RunDataset.is_sequencing:
I think you meant 
```python
while dataset.is_sequencing():
```

2017-03-03 14:01 UTC, tcezard commented on analysis_driver/dataset.py
> +        return clarity.get_run(self.name).udf.get('Run Status') == 'RunStarted'
Are we sure the run will exist in the LIMS?
What happen if it doesn't?

2017-03-21 11:10 UTC, mwhamgenomics requested changes

2017-03-21 11:10 UTC, mwhamgenomics commented on analysis_driver/dataset.py
> +app_logger = log_cfg.get_logger('versions')
Why the name 'versions'? Also this is only used in RunDataset, which is an AppLogger already, so may as well just do `self.warning` there, and you wouldn't need to import `log_cfg`

2017-03-21 11:10 UTC, mwhamgenomics commented on analysis_driver/quality_control/bcl_validation.py
> +app_logger = log_cfg.get_logger('util')
Again, don't need this app_logger.

2017-03-21 11:10 UTC, mwhamgenomics commented on analysis_driver/pipelines/demultiplexing.py
> -    time.sleep(900)
Moving the sleep to BCLValidator has made it a bit implicit - maybe comment there about leaving time for the Lims to update. Also, sleeping for an hour might be a bit much

2017-03-21 11:10 UTC, mwhamgenomics commented on analysis_driver/pipelines/demultiplexing.py
> +import os
Don't need this `import os` - join is already imported from os.path

2017-03-23 10:56 UTC, tcezard commented on analysis_driver/pipelines/demultiplexing.py
> -    time.sleep(900)
After Chatting with Murray we agreed that we should bring down the sleep time to 20min (approx 1 cycle)

2017-03-23 11:09 UTC, tcezard requested changes

2017-03-23 11:09 UTC, tcezard commented on analysis_driver/dataset.py
> +        return clarity.get_run(self.name).udf.get('Run Status') == 'RunStarted'
I just realised that the Run object in the genologics API will get cached and that the UDF `'Run Status'` will never change.
We should explicitly store and update the lims run object and update it at each call of `is_sequencing`
```python
@property
def lims_run(self):
    if not self._lims_run:
        self._lims_run = clarity.get_run(self.name)
    return self._lims_run

def is_sequencing(self):
    if not self.lims_run:
        self.warning('Run %s not found in the LIMS', self.name)
        return True
    # force the update of the LIMS object
    self.lims_run.get(force=True)
    return self.lims_run.udf.get('Run Status') == 'RunStarted'
```

2017-03-28 12:47 UTC, tcezard approved these changes

2017-03-28 12:52 UTC, tcezard requested changes

2017-03-28 12:52 UTC, tcezard commented on analysis_driver/pipelines/demultiplexing.py
>      run_status = clarity.get_run(run_id).udf.get('Run Status')
we should retrieve the status from the stored Lims object with
```python
if dataset.lims_run.udf.get('Run Status') != 'RunCompleted':
```
also remove the TODO as it is now taken care of

2017-03-28 19:38 UTC, tcezard approved these changes

2017-03-29 09:14 UTC, mwhamgenomics approved these changes

2017-03-29 09:28 UTC, merged