use egcg_core to get genome version
EdinburghGenomics/Analysis-Driver pull request #250
Opened 2017-05-16 11:02 UTC by katieemelianova

update egcg_core version within the new version of master

2017-05-16 13:40 UTC, mwhamgenomics requested changes

2017-05-16 13:40 UTC, mwhamgenomics commented on analysis_driver/dataset.py
> +            self._genome_version = clarity.get_genome_version()
`get_genome_version` takes a sample ID and species name

2017-05-30 13:25 UTC, tcezard requested changes
Could you fix this PR?

2017-06-13 15:35 UTC, mwhamgenomics approved these changes

2017-06-14 08:08 UTC, tcezard approved these changes

2017-06-14 08:16 UTC, merged