Test runcrawler
EdinburghGenomics/Analysis-Driver pull request #253
Opened 2017-05-26 12:23 UTC by katieemelianova

test for barcode updates where run_dir is provided to RunCrawler
resolves #251

2017-05-30 11:24 UTC, mwhamgenomics requested changes
Instead of pushing empty fastqfilterer files to Git, can we patch `_populate_barcode_info_from_fastq_filterer_files` in test_crawlers? Or better still, we could add data to the fastqfilterer files and test that.

2017-05-30 11:24 UTC, mwhamgenomics commented on analysis_driver/report_generation/report_crawlers.py
> +
?

2017-05-30 11:24 UTC, mwhamgenomics commented on analysis_driver/report_generation/report_crawlers.py
> +
?

2017-06-06 10:48 UTC, mwhamgenomics approved these changes

2017-06-06 15:06 UTC, tcezard approved these changes

2017-06-13 13:19 UTC, merged