Report in LIMS when a pipeline starts or finishes in a sample
EdinburghGenomics/Analysis-Driver pull request #269
Opened 2017-07-20 15:19 UTC by katieemelianova

Fix run_qc bug
update egcg_core to 0.7 in requirements

2017-07-21 09:28 UTC, mwhamgenomics requested changes

2017-07-21 09:28 UTC, mwhamgenomics commented on analysis_driver/dataset.py
> +        if self.type == 'sample': self.lims_ntf.fail_and_reset_sample_pipeline()
I'd have these in SampleDataset as additions to the default behaviour:

```python
class SampleDataset(Dataset):
    def abort(self):
        super().abort()
        self.lims_ntf.fail_and_reset_sample_pipeline()
```

2017-07-21 09:28 UTC, mwhamgenomics commented on analysis_driver/notification.py
> +from pyclarity_lims.lims import Step
This should be pyclarity_lims.entities. Also, this should be added to requirements.txt

2017-07-25 16:47 UTC, mwhamgenomics requested changes

2017-07-25 16:47 UTC, mwhamgenomics commented on analysis_driver/dataset.py
> +        self.lims_ntf.fail_and_reset_sample_pipeline()
Failing and resetting a successful pipeline?

2017-07-27 12:52 UTC, katieemelianova commented on analysis_driver/dataset.py
> +        self.lims_ntf.fail_and_reset_sample_pipeline()
Oops! Thanks for pointing that out, have changed it now

2017-07-27 15:47 UTC, mwhamgenomics requested changes

2017-07-27 15:47 UTC, mwhamgenomics commented on tests/test_dataset.py
> +        self.dataset.most_recent_proc.entity['status'] = c.DATASET_PROCESSING
Don't see why we're setting an item here when we're just `del`-ing it two lines later

2017-07-28 08:31 UTC, katieemelianova commented on tests/test_dataset.py
> +        self.dataset.most_recent_proc.entity['status'] = c.DATASET_PROCESSING
I forgot to delete that line, thanks for pointing out

2017-07-28 13:40 UTC, mwhamgenomics approved these changes

2017-08-02 15:18 UTC, tcezard requested changes

2017-08-02 15:18 UTC, tcezard commented on analysis_driver/notification.py
> +        self.sample_list = clarity.get_list_of_samples(self.name)
We should only retrieve one and only one sample here.
`clarity.get_sample()` would be more appropriate and we should check the return is not `None`

2017-08-02 15:18 UTC, tcezard commented on analysis_driver/notification.py
> +        self.artifacts = [sample.artifact for sample in self.sample_list]
Same as above, only one `artifact`

2017-08-02 15:18 UTC, tcezard commented on analysis_driver/notification.py
> +        return self.lims.get_workflows(name='PostSeqLab EG 1.0 WF')[0].stages
Put the workflow name in the config file.

2017-08-02 15:18 UTC, tcezard commented on analysis_driver/notification.py
> +        self.step = Step.create(self.lims, protocol_step=self.get_stage('Data Processing EG 1.0 ST').step, inputs=[self.artifacts], container_type_name='Tube')
If `self.artifacts` is a list then you would pass a list of of one list to inputs.
Make sure the artifact is properly passed to `route_artifacts` and  `inputs`

2017-08-02 15:18 UTC, tcezard commented on analysis_driver/notification.py
> +    def get_stage(self, stage_name):
The stage is the same across the entire run and does not need to be searched for every time.

2017-08-02 15:18 UTC, tcezard commented on analysis_driver/dataset.py
> +        self._lims_ntf = None
Does this need to be in `Dataset` if it is only going to be used in the `SampleDataset`

2017-08-02 15:20 UTC, tcezard requested changes
Also LimsNotification is not tested.
Can you add unit tests

2017-08-09 14:59 UTC, tcezard requested changes

2017-08-09 14:59 UTC, tcezard commented on tests/test_dataset.py
> +        self.assertTrue(mocked_lims_ntf.called)
This doesn't test that `start_sample_pipeline` was called

2017-08-09 14:59 UTC, tcezard commented on tests/test_dataset.py
> +        self.assertTrue(mocked_lims_ntf.called)
This doesn't test that `assign_next_and_advance_step` was called

2017-08-11 15:34 UTC, mwhamgenomics requested changes
Some changes from master were overwritten. These should be restored.

2017-08-11 15:34 UTC, mwhamgenomics commented on tests/test_dataset.py
> -
Hey, we needed that!

2017-08-11 15:34 UTC, mwhamgenomics commented on tests/test_dataset.py
> +        pass
This was removed in master, but seems to have crept back in during the merge. Can this be reverted, along with the removal of `patched_is_ready`?

2017-08-11 15:34 UTC, mwhamgenomics commented on tests/test_dataset.py
> -        }
Hey, we needed that!

2017-08-15 11:01 UTC, closed without merging