Project process md5
EdinburghGenomics/Analysis-Driver pull request #271
Opened 2017-08-14 15:17 UTC by katieemelianova

run md5sum after project process
closes #267

2017-08-14 16:09 UTC, mwhamgenomics requested changes

2017-08-14 16:09 UTC, mwhamgenomics commented on etc/example_analysisdriver.yaml
> +            dbsnp: /lustre/home/production/Applications/bcbio/0.9.8/genomes/Hsapiens/hg38/variation/dbsnp-147.vcf.gz
The 'references' config field was removed in #221. This should be:
```yaml
species:
    'Homo sapiens':
        default: a_genome

genomes:
    a_genome:
        fasta: path/to/genome.fa
        dbsnp: path/to/dbsnp.vcf.gz
```
`projects.build_pipeline` should then query this via `dataset.reference_genome`

2017-08-14 16:09 UTC, mwhamgenomics commented on tests/test_pipelines/test_projects.py
> +                                               working_dir='/Users/katie/PycharmProjects/Analysis-Driver/tests/assets/test_projects')
This is breaking the build.

2017-08-14 16:09 UTC, mwhamgenomics commented on analysis_driver/pipelines/projects.py
> +    return cfg.query('sample', 'delivery_source')
Looks like this is only called in one place - does it really need to be a function?

2017-08-14 16:09 UTC, mwhamgenomics commented on analysis_driver/pipelines/projects.py
> +        )
Also missing `toolset.write_to_yaml` for dependency version reporting. I'm feeling like version reporting and md5s should be a standard part of any data output, so there should be a generic DataOutput class in `pipelines.common` that puts all this alongside link creation and the call to output_data_and_archive.

2017-08-16 14:40 UTC, katieemelianova commented on analysis_driver/pipelines/projects.py
> +        )
I've added toolset.write_to_yaml though have left writing a generic DataOutput for another pull request

2017-08-17 13:17 UTC, mwhamgenomics approved these changes

2017-09-15 15:56 UTC, merged