Review trigger
EdinburghGenomics/Analysis-Driver pull request #287
Opened 2017-11-01 14:17 UTC by katieemelianova

Trigger automatic review after a run or a sample is finished processing

2017-11-16 16:49 UTC, mwhamgenomics requested changes

2017-11-16 16:49 UTC, mwhamgenomics commented on analysis_driver/pipelines/qc.py
> +    review = common.SampleReview, previous_stages=[cleanup]
This should be `common.SampleReview(dataset=dataset, previous_stages=[cleanup])`.

2017-11-17 16:24 UTC, katieemelianova commented
Requested preliminary review - changes needed here and to how the integration test works before this can be merged.

2017-11-17 16:26 UTC, mwhamgenomics approved these changes

2017-12-05 15:01 UTC, tcezard approved these changes

2017-12-05 15:49 UTC, katieemelianova commented
Pull request merged despite Coveralls failing: negligible decrease in code coverage.

2017-12-05 15:49 UTC, merged