Nonhuman variantcalling
EdinburghGenomics/Analysis-Driver pull request #319
Opened 2018-02-06 10:50 UTC by katieemelianova

Add variant calling to QC pipeline, and extract ti/tv and het/hom ratio from results
Also extract ti/tv and het/hom ratio from result of variant_calling pipeline
report these metrics in all sample pipelines

2018-02-06 14:06 UTC, mwhamgenomics requested changes

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +        if self.dbsnp:
If we don't have dbsnp for the species or if we forget to add it to the config, we'll be missing out on some annotation without knowing. Are we sure about this?

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +    def select_snp_command(self):
This can be pushed down to SelectVariants

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +    def filter_snp_command(self):
This can be pushed down to VariantFiltration

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +            self.command,
This doesn't need to be a parameter - can just use self.select_snp_command

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +            self.command,
This doesn't need to be a parameter - can just use self.filter_snp_command

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +    g = GATKStage(dataset=dataset)
We shouldn't really be creating instances of abstract classes like this. With the fixes above, it should be possible to remove this

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/qc.py
> +    g = v.GATKStage(dataset=dataset)
Kind of annoying that this is necessary, but works for now. Should probably look at cleaning up the handling of pipeline files later.

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/qc.py
> +    data_output = common.SampleDataOutput(dataset=dataset, previous_stages=[tabix], output_fileset='non_human_qc')
This can be a call to `stage()`

2018-02-06 14:06 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +class GenotypeGVCFs(GATKStage):
This basically duplicates relatedness.GenotypeGVCFs - should refactor later

2018-02-06 23:21 UTC, tcezard requested changes
Can you add unit tests at least for the new Classes/functions/properties.
It would also be goo to take the opportunity to add tests for other Stages

2018-02-14 10:25 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +
?

2018-02-14 10:38 UTC, mwhamgenomics commented on analysis_driver/pipelines/variant_calling.py
> +
?

2018-04-04 14:07 UTC, mwhamgenomics approved these changes

2018-04-13 19:58 UTC, tcezard approved these changes

2018-04-16 07:47 UTC, merged