Interop metrics
EdinburghGenomics/Analysis-Driver pull request #323
Opened 2018-02-14 14:17 UTC by tcezard

Run interop summary on the run folder then parse the output and upload to the reporting app.
Changed `RunCrawler` to only take a run directory instead of the multiple file.

2018-02-22 14:29 UTC, mwhamgenomics requested changes

2018-02-22 14:29 UTC, mwhamgenomics commented on tests/assets/interop_summary.txt
> +Scored: 302
This same test file exists three times in the repository - can we remove the duplicates?

2018-02-22 14:29 UTC, mwhamgenomics commented on tests/test_reader/test_demultiplexing_parsers.py
> +import egcg_core
Unused import

2018-02-26 14:03 UTC, katieemelianova approved these changes

2018-03-05 12:13 UTC, mwhamgenomics approved these changes

2018-03-06 13:58 UTC, merged