[WIP] Ensure all files have been transferred before starting run processing
EdinburghGenomics/Analysis-Driver pull request #393
Opened 2019-04-26 14:02 UTC by lukbut

From issue: 

In some cases, some bcl files were missing at the beginning of the Run processing due to the transfer lagging behind.
We should check that all the file are present and if they're not add another 5 mins wait.

Related to issues documented in NC163.

2019-04-30 03:24 UTC, tcezard requested changes

2019-04-30 03:24 UTC, tcezard commented on tests/test_quality_control/test_bcl_validation.py
> +        mocked_cycles.return_value = 3  # no completed cycles
This comment needs to be updated

2019-04-30 08:15 UTC, lukbut commented on tests/test_quality_control/test_bcl_validation.py
> +        mocked_cycles.return_value = 3  # no completed cycles
This has now been done. Well spotted!

2019-04-30 08:34 UTC, tcezard approved these changes

2019-04-30 08:34 UTC, tcezard commented
Validation ID: VB8

2019-05-01 15:21 UTC, mwhamgenomics approved these changes

2019-05-01 15:25 UTC, merged